-- phpMyAdmin SQL Dump
-- version 4.0.10.7
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Apr 18, 2015 at 03:15 PM
-- Server version: 5.5.42-cll
-- PHP Version: 5.4.23

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `boardsfo_dbus`
--

-- --------------------------------------------------------

--
-- Table structure for table `administrator`
--

CREATE TABLE IF NOT EXISTS `administrator` (
  `pk_administrator_id` int(11) NOT NULL AUTO_INCREMENT,
  `administrator_name` varchar(100) NOT NULL,
  `administrator_surname` varchar(100) NOT NULL,
  `administrator_email` varchar(100) NOT NULL,
  `administrator_password` varchar(100) DEFAULT NULL,
  `administrator_added` datetime NOT NULL,
  `administrator_last_login` datetime DEFAULT NULL,
  `administrator_updated` datetime NOT NULL,
  `administrator_active` tinyint(4) NOT NULL,
  `administrator_deleted` tinyint(4) NOT NULL,
  PRIMARY KEY (`pk_administrator_id`),
  UNIQUE KEY `administrator_email_UNIQUE` (`administrator_email`) USING BTREE,
  UNIQUE KEY `pk_administrator_id_UNIQUE` (`pk_administrator_id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=2 ;

--
-- Dumping data for table `administrator`
--

INSERT INTO `administrator` (`pk_administrator_id`, `administrator_name`, `administrator_surname`, `administrator_email`, `administrator_password`, `administrator_added`, `administrator_last_login`, `administrator_updated`, `administrator_active`, `administrator_deleted`) VALUES
(1, 'Saleem', 'Paleka', 'info@boardsforafrica.co.za', 'saleem12', '2011-04-22 05:56:39', '2014-12-21 15:59:34', '2014-12-21 15:59:34', 1, 0);

-- --------------------------------------------------------

--
-- Table structure for table `enquiry`
--

CREATE TABLE IF NOT EXISTS `enquiry` (
  `pk_enquiry_id` int(11) NOT NULL AUTO_INCREMENT,
  `enquiry_reference` varchar(255) DEFAULT NULL,
  `enquiry_name` varchar(255) DEFAULT NULL,
  `enquiry_email` varchar(255) DEFAULT NULL,
  `enquiry_subject` varchar(255) DEFAULT NULL,
  `enquiry_comments` text,
  `enquiry_added` datetime DEFAULT NULL,
  `enquiry_updated` datetime DEFAULT NULL,
  `enquiry_active` tinyint(1) DEFAULT NULL,
  `enquiry_deleted` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`pk_enquiry_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=93 ;

--
-- Dumping data for table `enquiry`
--

INSERT INTO `enquiry` (`pk_enquiry_id`, `enquiry_reference`, `enquiry_name`, `enquiry_email`, `enquiry_subject`, `enquiry_comments`, `enquiry_added`, `enquiry_updated`, `enquiry_active`, `enquiry_deleted`) VALUES
(1, 'HKN1-6H', 'mzimhle mosiwe', 'mzimhle.mosiwe@gmail.com', 'Help me buy wood test email', 'hello, i want to buy wood', '2013-05-16 09:23:54', NULL, 1, 0),
(3, 'TFHP-2X', 'Colin', 'colin@intra.co.za', '3 Kitchen Cupboard Doors', 'Attention - Casiem\r\n\r\nHi Casiem as per conversation , I would want the following doors if possible made :\r\n\r\n1 x ( 797 x 297 ) edged all round , two hinge holes on 1 long side \r\n2 x ( 447 x 797) edged all round , two hinge holes on 1 long side each \r\n\r\nWhite 16mm chipboard\r\n\r\nPlease let me know if any further details are required\r\n\r\nThanks', '2013-05-29 12:19:13', NULL, 1, 0),
(4, 'MH05-05', 'Tasneem - secure electronics', 'tasneem84@webmail.co.za', 'Urgent pricing', 'Good day,\r\nPlease quote me on the following:\r\nQty - dimensions\r\n1 - 2240mm X 460mm\r\n3 - 100mm X 1565mm\r\n2 - 100mm X 460mm\r\n10 - 775mm X 460mm\r\n\r\nBoard - white melamine\r\nEdging - normal\r\nThanking you and regards,\r\nTasneem', '2013-06-05 22:12:52', NULL, 1, 0),
(5, 'RVWM-TM', 'Hanks', 'hanks-guo@hotmail.com', 'Re:High gloss mdf boards,FROM:Hanks', 'Dear Sir ,\r\nGood day, we are factory of high gloss PETG and Acrylic mdf board widely used to  kitchens, wardrobes ,interiors deco,etc. The products include the wood grain color, solid color, shining color, Embossment/patterns, PETG board and Acrylic mdf board. \r\n \r\nWe can send our samples with catalogues for your check.\r\nPlease check our website: www.zpuv.com  We hope you take interest in our products . boards size:2440*1220*18/16/9mm. \r\n \r\nAwait for your feedback.Thanks a lot.  \r\nBest Regards \r\nHanks.Guo\r\nTel/Fax: 0086+021+51208384/59586078', '2013-06-10 06:12:33', NULL, 1, 0),
(6, '6R1Q-U5', 'meagan diedericks', 'meagan8@cellc.blackberry.com', 'rhino board', 'I would like to know the prices of the rhino board for seiling 3m by 1,25m and how much is ur earolite a roll plz', '2013-06-17 09:11:40', NULL, 1, 0),
(7, 'YMNI-DX', 'xuzhou centurywood co.,ltd.', 'centurywood@centurywood.cn', 'offer plywood from China', 'Dear Sir/Madam,                                       \r\n \r\nNice to see you!\r\n \r\nI come from XUZHOU CENTURYWOOD CO.,LTD. We take this opportunity to write to you with a view to set up friendly business relation with you. We are PROFESSIONAL company dealing specially with the export of plywood, Fancy plywood, OSB board, finger jointed panels,  we have been exporters of plywood for many years,if you want to kown the more information of the plywood,\r\nplease contact by email. Please see below our products: \r\n \r\nFancy plywood/Decorative plywood\r\nSize: 1220X2440mm, 1250X2500mm, 1250X3050mm\r\n\r\nThickness: 3/4/6/9/12/15/18mm, up to 40mm\r\n\r\nWood species: White oak, Red oak, Ash, Sapelli, Beech, Maple, Cherry, Teak, Walnut, etc.\r\n\r\nGlue: E1, E2, WBP\r\n\r\nCore: poplar core, hardwood core, birch core, as for order.\r\n\r\nGrade: A-1, B-2, C-3,A/B, B/C, C/D\r\n\r\nCutting: Sliced cut (0.2 mm-0.35 mm, 0.35mm-1.2mm), rotary cut (0.50 mm-0.70 mm)\r\nEnd use: For high grade furniture\r\n\r\n \r\n\r\n \r\n\r\nPLYWOOD\r\n\r\n1) FILM FACED PLYWOOD / WIRE MESH PLYWOOD/Plastic film faced plywood\r\n\r\nSIZE: 1220X2440mm, 1250x2500mm, 1500X3000mm, 1525x3050mm, 2000x6000mm\r\nThicknessï¼š6mm,9mm, 12mm, 15mm, 18mm, 21mm\r\nGlue: WBP \r\nCORE: POPLAR, BIRCH, HARDWOOD \r\nMOISTURE: BELOW 12%\r\nTHICKNESS TOLERANCE: +/-0.3MM\r\n \r\n2) BINTANGOR/OKOUME FACED PLYWOOD\r\nSIZE: 1220X2440mm, 1250x2500mm, 1500X3000mm, 1525x3050mm and other oversize\r\nThicknessï¼š3.6mm, 6mm,9mm, 12mm, 15mm, 18mm, 21mm\r\nGlue: MR, MELAMINE, WBP \r\nCORE: POPLAR, BIRCH, HARDWOOD \r\nMOISTURE: BELOW 12%\r\nTHICKNESS TOLERANCE: +/-0.3MM\r\n \r\n \r\n3) BIRCH FACED PLYWOOD/BIRCH THROUGHOUT PLYWOOD\r\nSIZE 1220X2440mm, 1250x2500mm, 1500X3000mm, 1525x3050mm and other oversize\r\nThicknessï¼š3.6mm, 6mm,9mm, 12mm, 15mm, 18mm, 21mm\r\nGlue: MR, MELAMINE, WBP \r\nCORE: POPLAR, BIRCH, HARDWOOD \r\nMOISTURE: BELOW 12%\r\nTHICKNESS TOLERANCE: +/-0.3MM\r\n \r\n4) FLOOING BASE PLYWOOD/ TONGUE & GROOVE PLYWOOD\r\nSIZE AND THICKNESS ACCORDING TO ORDER REQUEST\r\n \r\n5) Pine LVL, Poplar LVL, Hardwood LVL\r\n\r\nLength: up to 6030MM\r\n\r\nThickness and width according to order\r\n\r\n \r\n\r\n \r\n\r\nPlease let us know immediately if you are interested in our products,we will send your our price list to you as soon as we receive your specific inquiry. \r\nLooking forward to hear from you.\r\nBest Regards,\r\nAmy xu\r\n \r\nTEL: 0086-516-87828632\r\nFAX: 0086-516-83798893\r\n \r\nXUZHOU CENTURYWOOD CO.,LTD\r\nWEB:WWW.CENTURYWOOD.CN', '2013-06-19 09:39:39', NULL, 1, 0),
(8, 'YOFE-6L', 'desiree kloppers', 'dezi30dtp@yahoo.com', 'different types of boards and prices', 'Hi , can you please send me a list of your different types of boards and prices of it all.\r\nThank You\r\n\r\nDesiree\r\n\r\nDesiree', '2013-06-24 15:49:16', NULL, 1, 0),
(9, 'KZQ3-90', 'Hanks Guo', 'hanks-guo@hotmail.com', 'High gloss mdf board cooperation', 'Dear Sir,\r\nGood day, we are factory of high gloss mdf board widely used to  kitchens, wardrobes ,interiors deco,etc. The products include the wood grain color, solid color, shining color, Embossment/patterns, PETG board and Acrylic mdf board. \r\n \r\nWe can send our samples with catalogues for your check.\r\nPlease check our website: www.zpuv.com  We hope you take interest in our products . boards size:2440*1220*18/16/9mm. \r\n \r\nAwait for your feedback.Thanks a lot.  \r\nBest Regards \r\nHanks.Guo\r\nTel/Fax: 0086+021+59586078/59586557', '2013-06-27 10:20:37', NULL, 1, 0),
(10, 'CG3N-YH', 'Keshia Trussell', 'keshia.trussell@uct.ac.za', 'Prices', 'Good day, \r\nCould you give me the price of the following:\r\nChipboard\r\nChipboard melamine faced\r\nMDF melamine faced\r\n\r\n\r\nKind regards, \r\nKeshia', '2013-07-22 11:53:01', NULL, 1, 0),
(11, 'EU3G-YJ', 'Dean Moses', 'dazmo24@gmail.com', 'White Melamine Board Price', 'Can you please tell me the price for the white melamine board.  I will have it cut and edged as well.', '2013-08-08 13:19:02', NULL, 1, 0),
(12, 'OPDF-4R', 'Dean Moses', 'dazmo24@gmail.com', 'White Melamine Board Price', 'Can you please tell me the price for the white melamine board.  I will have it cut and edged as well.', '2013-08-08 13:19:02', NULL, 1, 0),
(13, 'SNKV-YY', 'igshaan adams', 'igshaan88@gmail.com', 'quotation', 'hi there  \r\ni need a quote for the following measurements\r\n\r\nin royal mahogany \r\n2345 X 600 X 4  impact edging\r\n2545 x 550 x 1\r\n2420 x 100 x 1\r\n1178 x 100 x 4\r\n550  x 100 x 1\r\n\r\nthe following in white melamine with mahogany edging\r\n2545 x 550 x 3\r\n1178 x 550 x 7\r\n1830 x 550 x 1\r\n581  x 550 x 6\r\n581  x 532 x 6\r\n472  x 225 x 12\r\n556  x 225 x 12\r\n556  x 472 x 6\r\n571  x 267 x 6\r\n\r\nthanks\r\nIgshaan', '2013-08-12 17:01:00', NULL, 1, 0),
(14, 'F1V7-72', 'Rebecca Li', 'rebecca@sunbird.com.cn', 'Re: Particle board/MDF manufacturer-Hebei Golden Sunbird', 'Dear Sir/Madam,\r\n \r\nWe are Hebei Golden Sunbird Trading Co., Ltd., a professional manufacturer of wood-based panels in China.  \r\n \r\nOur products include particle boards(chipboards), medium density fiberboards(MDF), melamine boards, hardboards etc. Their usage range: packaging, furniture, home decoration etc. Good quality, timely delivery can be assured by our factory.\r\n \r\nIf you are interested in our products, please give me a reply. We are looking forward to establishing business relationship with your company.\r\n\r\nThanks for reading my letter.\r\n\r\nHave a nice day.\r\n \r\nBest Regards,\r\nRebecca\r\nHebei Golden Sunbird Trading Co., Ltd.\r\nSkype: sunbird-sales01\r\nMSN: sunbird-sales01@hotmail.com', '2013-08-17 09:15:07', NULL, 1, 0),
(15, '0LYT-BO', 'Rebecca Li', 'rebecca@sunbird.com.cn', 'Re: Particle board/MDF manufacturer-Hebei Golden Sunbird', 'Dear Sir/Madam,\r\n \r\nWe are Hebei Golden Sunbird Trading Co., Ltd., a professional manufacturer of wood-based panels in China.  \r\n \r\nOur products include particle boards(chipboards), medium density fiberboards(MDF), melamine boards, hardboards etc. Their usage range: packaging, furniture, home decoration etc. Good quality, timely delivery can be assured by our factory.\r\n \r\nIf you are interested in our products, please give me a reply. We are looking forward to establishing business relationship with your company.\r\n\r\nThanks for reading my letter.\r\n\r\nHave a nice day.\r\n \r\nBest Regards,\r\nRebecca\r\nHebei Golden Sunbird Trading Co., Ltd.\r\nSkype: sunbird-sales01\r\nMSN: sunbird-sales01@hotmail.com', '2013-08-17 09:15:09', NULL, 1, 0),
(16, 'UOEW-HE', 'Siphelo', 'siphelomona@gmail.com', 'Opening hours', 'Good day,\r\n\r\nI would like to know what are your opening hours on weekends?\r\n\r\nThank you', '2013-10-02 11:51:04', NULL, 1, 0),
(17, 'CZ5Z-G6', 'kobus nel', 'kobus33333@gmail.com', 'boards', 'Hi need price and size on 3 ply boards thanks', '2013-10-14 08:13:57', NULL, 1, 0),
(18, 'U73O-J0', 'RUTH', 'RUTH@BLOCKANDCHISEL.CO.ZA', 'QUOTATION', 'HI iAM JUST DOING AN  FOLLOW UP  ABOT THE ABOVE.CLIENT MARLIN. HENEED THE QOUATION AS SOON AS POSSIABLE.\r\nLOOKING FORWARD TO HEAR FROM YOU.\r\nREGARDS.\r\nrUTH.', '2013-10-30 14:15:56', NULL, 1, 0),
(19, 'IC1K-BT', 'RUTH', 'RUTH@BLOCKANDCHISEL.CO.ZA', 'QUOTATION', 'HI iAM JUST DOING AN  FOLLOW UP  ABOT THE ABOVE.CLIENT MARLIN. HENEED THE QOUATION AS SOON AS POSSIABLE.\r\nLOOKING FORWARD TO HEAR FROM YOU.\r\nREGARDS.\r\nrUTH.', '2013-10-30 14:15:56', NULL, 1, 0),
(20, 'LUFN-K9', 'marlin de kock', 'marlin.dekock@capetown.gov.za', 'quotation enquiry', 'good day, \r\ncould you forward a list of available veneers for cupboards to my e-mail adress please.\r\n\r\nalso would it be possible to generate a quotation from a MS Excel document sent via e-mail?\r\n\r\nthank you\r\n\r\nmdekock', '2013-11-04 10:45:34', NULL, 1, 0),
(21, 'F18Z-Z5', 'marlin de kock', 'marlin.dekock@capetown.gov.za', 'quotation enquiry', 'good day, \r\ncould you forward a list of available veneers for cupboards to my e-mail adress please.\r\n\r\nalso would it be possible to generate a quotation from a MS Excel document sent via e-mail?\r\n\r\nthank you\r\n\r\nmdekock', '2013-11-04 10:45:34', NULL, 1, 0),
(22, 'CIYR-OX', 'moidean', 'moideanpalmo@gmail.com', 'backing board', 'fatima\r\n\r\nim still waiting for an answer', '2013-11-11 15:41:37', NULL, 1, 0),
(23, '3VNO-JS', 'Tamryn', 'tamrynb@polo.co.za', 'Kitchen Gloss Boards', 'Good Day\r\n\r\nI wanted to check whether you sell your products and service on credit, like over 3/6 month payback?\r\n\r\nPlease advise\r\nKindest Regards,\r\nTamryn', '2013-11-18 12:58:26', NULL, 1, 0),
(24, 'CTG2-HE', 'Charles', 'plywoodmanufacture@126.com', 'Re:plywood', 'Dear Purchase manager, \r\n\r\nGlad to learn you''re on the South Africa market  as one of  big distributor,importer for plywood items.\r\n\r\nWe are a leading manufacture of plywood,film faced plyowod,OSB,wood veneer items with CARB P2 certificated.\r\n\r\nCurrently we alrady have cooperation with Interwil panel agency ,it is also big distributor in South Africa .\r\n\r\n \r\n\r\nIf you interested feel free let me know your detail inquiry ,I will give you the best quotation.\r\n\r\n \r\n\r\nOur products can be used on furniture,packing and building material etc.\r\n\r\n\r\nHope to find a way to work with you,Waiting for your contact to discuss the possible deal.\r\n\r\nBest Regards\r\n\r\nCharles\r\n\r\nExport Manager\r\n\r\nCellphone :86-18253955898(Available Whatsapp and Viber)\r\n\r\nSkype plywoodmanufacture\r\n\r\nhttp://woodsply.weebly.com\r\n\r\nP Please consider the environment before printing this e-mail.\r\n\r\nAlso can offe your best inspection service if your company needed.', '2013-12-10 10:02:39', NULL, 1, 0),
(27, '9Y69-CA', 'Abdurahman Daniels', 'Abdurahman.daniels@westerncape.gov.za', 'Quote', 'Good morning\r\n\r\nKindly provide a quotation for the following:\r\n\r\nWHITE MELOMINE\r\n\r\nÂ§	4@ 2380x600 -  Edge 1 long\r\nÂ§	6@1068x600. -  Edge 1 long\r\nÂ§	2@868x590.   -  Edge 1 long\r\nÂ§	2@500x590.   -  Edge 1 long 1short\r\nÂ§	1@1748x600. -  Edge 1 long\r\nÂ§	8@524x550.   -  Edge 1 short\r\nÂ§	2@1800x100. -  Edge 1 long\r\nÂ§	2@1068x100\r\nÂ§	3@1068x120\r\n\r\nDOORS\r\n\r\nÂ§	4@2270x546- Edge all round(4hinge holes each)\r\nÂ§	2@490x446-   Edge all round(2hinge holes each)(490)\r\nÂ§	2@1760x446- Edge all round(3hinge holes each)(1760)\r\n\r\nWHITE MASONITE\r\n\r\nÂ§	2@2280x1100\r\nÂ§	1@900x500\r\n\r\n26 straight concealed hinges\r\n\r\nThank you', '2014-01-13 09:01:27', NULL, 1, 0),
(28, '7XOT-L4', 'Rukieya Mohamed', 'rukieya.mohamed@wns.com', 'Price List', 'Hi there, do you have a document you can email me with all the colour boards you have and the pricing, impact edging and size? before i need to drive there please let me know', '2014-01-15 11:54:57', NULL, 1, 0),
(29, 'LEI7-5N', 'Khaleel de Vries', 'khaleel.devries@gmail.com', 'Quote', 'Hi\r\n\r\nCan you please quote on the following:\r\n\r\nWhite Melamine: Cream Edging\r\n792 x 300 = 1 EAR (2H)\r\n2114 x 596 = 1 EAR (4H)\r\n450 x 471 = 2 EAR (2H)\r\n780 x 120 = 2 E/L (E25)\r\n120 x 618 = 2 E/L\r\n792 x 350 = 1 EAR\r\n468 x 450 = 4 E/L\r\n950 x 450 = 1 E/L\r\n450 x 300 = 2 E/L (E25)\r\n918 x 300 = 2 E/L\r\n918 x 280 = 1 E/L\r\n\r\nHigh Gloss Wrap Doors:\r\n2480 x 496 = 3 (4H)\r\n2480 x 474 = 2 (4H)\r\n700 x 449 = 2 (3H)\r\n1774 x 449 = 2 (3H)', '2014-01-28 12:46:51', NULL, 1, 0),
(30, 'ST0C-XY', 'Khaleel de Vries', 'khaleel.devries@gmail.com', 'Quote', 'Hi\r\n\r\nCan you please quote on the following:\r\n\r\nWhite Melamine: Cream Edging\r\n792 x 300 = 1 EAR (2H)\r\n2114 x 596 = 1 EAR (4H)\r\n450 x 471 = 2 EAR (2H)\r\n780 x 120 = 2 E/L (E25)\r\n120 x 618 = 2 E/L\r\n792 x 350 = 1 EAR\r\n468 x 450 = 4 E/L\r\n950 x 450 = 1 E/L\r\n450 x 300 = 2 E/L (E25)\r\n918 x 300 = 2 E/L\r\n918 x 280 = 1 E/L\r\n\r\nHigh Gloss Wrap Doors:\r\n2480 x 496 = 3 (4H)\r\n2480 x 474 = 2 (4H)\r\n700 x 449 = 2 (3H)\r\n1774 x 449 = 2 (3H)', '2014-01-28 12:46:52', NULL, 1, 0),
(31, '99E2-DM', 'rozina', 'rozina.plaatjies@hartrodt.co.za', 'rhino boards', 'please advise the price of your rhino boards 6mm 2.4 x 1.2 each....or alternatively 4.8 x 1.2/5', '2014-01-28 15:16:48', NULL, 1, 0),
(32, 'OPEI-UA', 'ledibohong trading', 'george@ledibohong.co.za', 'branch in pretoria', 'Do you have a branch in Pretoria area?if you do please give me their address.\r\n0835963426\r\nRegards\r\nGeorge', '2014-02-06 08:17:48', NULL, 1, 0),
(33, '6KQD-5K', 'sandra olivier', 'sandraoliver334@gmail.com', 'pricing catalogue', 'good day\r\ncan you please send me a pricing list of the different melamine boards...\r\n\r\nmany thanks\r\ns olivier', '2014-02-10 18:43:29', NULL, 1, 0),
(34, 'GT6P-V7', 'Keenan Petersen', 'keenanpetersen@hotmail.com', 'Quote', 'Whats the price of the white white melamine>', '2014-02-13 08:38:26', NULL, 1, 0),
(35, 'E6IK-L7', 'Siraj Braaf', 'Sirajdo@yahoo.com', 'Quote', 'Hi\r\nPlease contact me asap. I want to email a material cutting list for quote asap.', '2014-02-14 16:00:07', NULL, 1, 0),
(36, '8WJE-C1', 'F.Naidoo', 'info@xenocorp143.co.za', 'Quote', 'Can you give me Quote for a job called â€œMikeâ€™s Projectâ€\r\nFor white PVC â€“Warp doors â€“ see sizes below :-\r\n\r\nWhite PVC Warp Doors & draws	3500\r\n	 	 	 \r\n2200	x	425	1\r\n1100	x	425	2\r\n900	x	550	1\r\nDraws - 400	x	150	2\r\n650	x	400	2\r\n800	x	400	2\r\n800	x	700	1\r\n\r\nthanx\r\nfahiem', '2014-02-18 23:21:46', NULL, 1, 0),
(37, 'FQGR-DE', 'Denise Wu', 'denisewu1518@gmail.com', 'mdf,plywood,particle board,cabinet', 'Dear friend,\r\nGlade to hear that youâ€™re on the market for MDF .\r\nThis is BLMA from China, have manufactured (plywood, mdf, particle board and all kinds of panel furnitures) for more than 10 yearsï¼Œwith good quality and pretty competitive price.\r\n\r\nAny reply from you will be high appreciation.\r\nThanks and warm regards.\r\nDenise', '2014-03-05 07:30:41', NULL, 1, 0),
(38, '4H2R-G2', 'Denise Wu', 'denisewu1518@gmail.com', 'mdf,plywood,particle board,cabinet', 'Dear friend,\r\nGlad to hear that you are on the market of MDF.\r\nProfessional in MDF for nearly 10 years with high quality and competitive prices. We have our own MDF board factory in China , and have a branch in Zambia.\r\nAny questions ,you can contact me free.\r\nBest wishes for you.\r\nDenise', '2014-03-12 10:18:47', NULL, 1, 0),
(39, 'VGT9-SZ', 'Shameem Williams', 'shameemw@tfg.co.za', 'postform std size thickness counter tops', 'can you supply me with a price list of the postform counter tops and colours as soon as possible please?', '2014-03-13 13:05:24', NULL, 1, 0),
(40, '1UHR-BF', 'Jonathan Hermanus', 'rio.oranje@gmail.com', 'Board to used in marching competition', 'Good day,please advise if it would be possible for you guys to do a board for our annual marching competition.We are using Sagex and we want the CODE OF ARMOUR(back of the coin)to be cut out. Please advise if you are not sure you call me on 0728252092.', '2014-03-14 13:15:30', NULL, 1, 0),
(41, 'DHU7-RW', 'Jonathan Hermanus', 'rio.oranje@gmail.com', 'Board to used in marching competition', 'Good day,please advise if it would be possible for you guys to do a board for our annual marching competition.We are using Sagex and we want the CODE OF ARMOUR(back of the coin)to be cut out. Please advise if you are not sure you call me on 0728252092.', '2014-03-14 13:17:17', NULL, 1, 0),
(42, 'E10K-2I', 'Jonathan Hermanus', 'rio.oranje@gmail.com', 'Board to used in marching competition', 'Good day,please advise if it would be possible for you guys to do a board for our annual marching competition.We are using Sagex and we want the CODE OF ARMOUR(back of the coin)to be cut out. Please advise if you are not sure you call me on 0728252092.', '2014-03-14 13:17:47', NULL, 1, 0),
(43, 'O0UX-E7', 'Nicole Shaer', 'Nicole.shaer@gmail.com', 'Ceiling Boards', 'Hi,\r\n\r\nI''ve tried calling, but there is no answer...\r\n\r\nI am looking for 3-6 ceiling boards of 1.2 x 3m to line a studio wall (to use as smooth work surface / pin board). \r\n\r\nCan you tell me if you supply ceiling boards, if there are different kinds , the cost, whether you can cut one of them for me and how much you''d charge to deliver to CBD. Also, could you deliver tomorrow? \r\n\r\nThanks,\r\nNicole', '2014-03-17 13:21:32', NULL, 1, 0),
(44, 'W5W1-YG', 'Jennelle'' Matle', 'jennelle@dlonra.co.za', 'price per meter', 'do you sell double trunkings for windows? if you do , what is your price per meter please', '2014-03-31 11:40:59', NULL, 1, 0),
(45, 'SJG7-0P', 'Ferdous samaai', 'Ferdous.samaai@gmail.com', 'Banking details', 'Hi please forward me banking details so I can make payment', '2014-04-07 10:42:18', NULL, 1, 0),
(46, 'DTQZ-NV', 'JL Ferreira', 'homelandfilemanagement@gmail.com', 'Quotation', 'Hi \r\nI need a quote on the following items:\r\n2 x white melamine chip boards\r\n1 x 3.5m flat top\r\n12 sets of hinges\r\n8 sets of small black nickle handles\r\n8 sets of meduim black nickle handles\r\n6 sets of draw  runners', '2014-04-14 22:49:32', NULL, 1, 0),
(47, 'HHCR-V9', 'Zohan Smith', 'zohan.smith@zyteqtechnologies.com', '18mm Shutter Ply', 'Good day,\r\n\r\nPlease supply me with a quotation for the following:\r\n\r\n1x 18mm Shutter Ply 1970mm x 1165mm\r\n5x 18mm Shutter Ply 1970mm x 1485mm\r\n\r\nRegards,\r\n\r\nZohan Smith', '2014-04-24 14:02:33', NULL, 1, 0),
(48, 'CD4I-OG', 'Lisa', 'wphkupjwa@gmail.com', 'Lisa', 'You need targeted visitors for your website so why not get some for free? There is a VERY POWERFUL and POPULAR company out there who now lets you try their traffic service for 7 days free of charge. I am so glad they opened their traffic system back up to the public! Check it out here: http://axr.be/17r1\r\nLisa http://axr.be/17r1', '2014-04-25 03:42:07', NULL, 1, 0),
(49, 'C5DQ-YW', 'Zakiyah Ebrahim', 'zakiyahebrahim@yahoo.com', 'Quote on melamine boards', 'To whom it may concern,\r\n\r\nI urgently require a quote for (plain white standard)/melamine boards (with edging) for carcasses from your store. Herewith the measurements:\r\n\r\n6/ 2600x570 - EIL\r\n10/ 968x570 - EIL\r\n3/ 368x570 - EIL\r\n6/ 500x120 - EIL\r\n6/ 904x120 - EIL\r\n3/ 940x150 - EAR\r\n8/ 520x70 - EIL\r\n3/ 468x120 - EIL\r\n\r\nBacking:\r\n\r\n2/ 2480x1000\r\n1/ 2480x400\r\n3/ 936x500\r\n\r\nAlso, if you deliver, is it at an additional cost and on the same day that payment is made? Please quote a delivery fee to Belgravia Estate, Athlone.\r\n\r\nKind regards,\r\nZakiyah Ebrahim.', '2014-05-03 12:28:04', NULL, 1, 0),
(50, 'IAS6-HB', 'vicky wang', 'vicky106905@gmail.com', 'chipboard and plywood', 'Dear friend, \r\nGood day!\r\nOur factory is a professional plywood and chip board manufacturer with years''s experience.So we want to avail ourselves of opportunity establishing business relation with you.\r\n\r\nWe have office in South Africa, any questions, they can also provide help for you.\r\n\r\nWe look forward to hearing from you soon.\r\n\r\nThank you and best regards,\r\nVicky', '2014-05-07 09:42:48', NULL, 1, 0),
(51, 'HYBI-99', 'Randall Woods', 'randallw@hho.co.za', 'wall cupboard quote needed', 'colour  Royal cherry			\r\n				\r\n3	720x325x16		1L/1S	\r\n2	568X300X16		1L/1S	\r\n2	450X296X16		A/R	2mm\r\n2	720X296x16		A/R	2mm\r\n1	720X496x16		A/R	2mm\r\n1	720X446x16		A/R	2mm\r\n2	400X296X16		A/R	2mm\r\n2	720X400X16		1L/1S	\r\n2	596X400X16		1L/1S	\r\n2	300X296X16		A/R	2mm\r\n3	300X300X16			\r\n				\r\n	white			\r\n				\r\n6	720x300x6		1L/1S	\r\n7	568X300X16		1L	\r\n2	450X300X16		1L/1S	\r\n3	418X300X16		1L	\r\n3	468X300X16		1L	\r\n				\r\n	Hardboard			\r\n				\r\n3	720x450			\r\n3	720x600			\r\n1	720x500', '2014-05-12 16:21:22', NULL, 1, 0),
(52, '7GZC-4O', 'shaukat parkar', 'shaukat@ugc.com.sa', 'Gypsum board', 'Dear sir,\r\nwe would introduce our self that we are largest Gypsum board and Gypsum powder manufacturing company in Saudi Arabia, we are planning to export our all grade product to South Africa region so currently  we are looking whole seller or distributors in South Africa. kindly lets us know your interest in the same.  \r\nkindly advise if need more information from our end\r\n\r\nEng. Shaukat Parkar\r\nPlant  Manager\r\nDirect Tel  -00966 14 3256074\r\nï€© +966 14 3968777 Ext. 103   ï€¶ +966 14 3962666 \r\nMobile   +966 541735968    \r\nï€ª P.O. Box 31491 Yanbu  51000 KSA \r\nwww.ugc.com.sa', '2014-05-13 15:25:58', NULL, 1, 0),
(53, 'OZKG-K6', 'jane Saviery', 'janesaviyeri@yahoo.com', 'enquiry', 'Dear sir\\madam\r\nI''m trying to come to your place.I''m getting lost. Can you give me specific directions\r\n \r\nThank yo', '2014-05-30 14:32:42', NULL, 1, 0),
(54, 'YQGW-EO', 'yusuf Kamies', 'yusufkamies@gmail.com', 'poor service', 'I came to you bussiness an hr ago to place an order for a kitchen top and what pathetic service l got from your sales person. Really not good for your business.', '2014-06-02 15:39:29', NULL, 1, 0),
(55, 'HUUH-Y9', 'Karen', 'zgapytn@gmail.com', 'Karen', 'We have made the decision to open our POWERFUL and PRIVATE website traffic system to the public for a limited time! You can sign up for our UP SCALE network with a free trial as we get started with the public''s orders. Imagine how your bank account will look when your website gets the traffic it needs. Visit us today: http://linksilo.com/4p\r\nKaren http://l.bruggers.net/hi26', '2014-06-05 14:51:27', NULL, 1, 0),
(56, 'RBL2-68', 'Faranaaz', 'faranaazbardien915@gmail.com', 'Catelogue', 'Can you please provide a price list or catalogue of you boads', '2014-06-17 12:44:48', NULL, 1, 0),
(57, 'Z4US-SC', 'Morty', 'support@superbsocial.net', 'I stumbled upon your site www.boardsforafrica.co.za', 'Hello, my name is Morty Goldman; I just stumbled upon your site - www.boardsforafrica.co.za - I''m sorry to write in such an odd manner, I thought to call you but I didn''t want to take up your time. What I have to say may be of great interest to you. Did you know that an overwhelming majority of businesses, organizations and celebrities buy likes and followers? What, you thought your competitor''s likes and followers are organic and naturally gained? Ha ha. Just recently Gangman Style ( http://www.youtube.com/watch?v=9bZkp7q19f0 ) reached a record 2 billion views. Now imagine the scale of Gangnam Style''s popularity being applied to your business! This is exactly how I deliver results to my clients - and I assure you that you''ll be overwhelmingly pleased with the outcome. \r\n \r\nGive us a call: +1 (877) 410-4002 \r\nor visit us at http://www.SuperbSocial.net', '2014-06-24 22:13:46', NULL, 1, 0),
(58, '2YFD-BF', 'Rayyaan Essa', 'rayyaane@nolitha.co.za', 'Request fro Quotation', 'Hi, Please ask Nazeem to contact me on 0829292289 as a matter of urgency. All your numbers are just ringing??', '2014-06-30 13:29:22', NULL, 1, 0),
(59, '3TPH-ON', 'Morty', 'support@superbsocial.net', 'I stumbled upon your site www.boardsforafrica.co.za', 'Hello, my name is Morty Goldman; I just stumbled upon your site - www.boardsforafrica.co.za - I''m sorry to write in such an odd manner, I thought to call you but I didn''t want to take up your time. What I have to say may be of great interest to you. Did you know that an overwhelming majority of businesses, organizations and celebrities buy likes and followers? What, you thought your competitor''s likes and followers are organic and naturally gained? Ha ha. Just recently Gangman Style ( http://www.youtube.com/watch?v=9bZkp7q19f0 ) reached a record 2 billion views. Now imagine the scale of Gangnam Style''s popularity being applied to your business! This is exactly how I deliver results to my clients - and I assure you that you''ll be overwhelmingly pleased with the outcome. \r\n \r\nGive us a call: +1 (877) 410-4002 \r\nor visit us at http://www.SuperbSocial.net', '2014-07-05 07:47:10', NULL, 1, 0),
(60, 'TYUR-N9', 'sadia boltman', 'sadiab3@gmail.com', 'quote', 'Att Saliem Jamodien\r\n\r\nWhite melamine commercial\r\n4x1440x695 edge all round\r\n10x1338x75 edge 1 long\r\n5x1440x75 edge 1 long n 2 short\r\n8x340x75 edge 1 long\r\n100 corner blocks\r\n100x8x40 chipboard screws\r\n400x8x16 chipboard screws\r\n\r\nShukran. Sadia 0823356431', '2014-07-07 15:42:35', NULL, 1, 0),
(61, 'P25F-E1', 'Shahnaaz Abdullah', 'shahnaaz.arnold@gmail.com', 'URGENT quotation', 'White Melamine Board \r\nSides                           :       6 * 2300 * 600 E1L\r\nTop & Bottoms         :       6 * 868 * 600 E1L 										 3 * 418 * 600 E1L\r\nDivisions                    :       2 * 1600 * 600 E1L\r\nShelves                      :       12 * 580 * 424 E1S										3 * 580 * 416 E1S\r\nBase                           :       2 * 2400 * 100\r\nFiller Piece         	       :       2 * 2200 * 100\r\nTop Filler                   :       2 * 2750 * 160\r\nWhite Hardboard Backing:	2 * 2200 * 896											1 * 2200 * 496\r\nWhite Melamine Doors:            5 * 2200 * 446 EAR 4 Holes\r\nHardware:	20 Hinges											6*16 Screws											8*16 Screws											6*30 Screws											8*40 Screws											Shelf Studs											2*White Painters Mate										Screw Caps', '2014-07-09 07:11:02', NULL, 1, 0),
(62, 'V8IH-JC', 'Morty', 'support@superbsocial.net', 'I stumbled upon your site www.boardsforafrica.co.za', 'Hello, my name is Morty Goldman; I just stumbled upon your site - www.boardsforafrica.co.za - I''m sorry to write in such an odd manner, I thought to call you but I didn''t want to take up your time. What I have to say may be of great interest to you. Did you know that an overwhelming majority of businesses, organizations and celebrities buy likes and followers? What, you thought your competitor''s likes and followers are organic and naturally gained? Ha ha. Just recently Gangman Style ( http://www.youtube.com/watch?v=9bZkp7q19f0 ) reached a record 2 billion views. Now imagine the scale of Gangnam Style''s popularity being applied to your business! This is exactly how I deliver results to my clients - and I assure you that you''ll be overwhelmingly pleased with the outcome. \r\n \r\nGive us a call: +1 (877) 410-4002 \r\nor visit us at http://www.SuperbSocial.net', '2014-07-11 19:40:48', NULL, 1, 0),
(63, 'UYAS-G3', 'tougieda galant', 'tougiedagallie@yahoo.com', 'times', 'What times are you open', '2014-07-18 15:14:40', NULL, 1, 0),
(64, 'W7PK-VA', 'Joseph', 'josephw@telkomsa.net', 'Quote', 'Good day, I need a quote for kitchen cupboards, Super wood devin doors,aluminium doors with frosted glass,hinges and telescopic drawer rails,melamine wood.', '2014-07-19 14:14:16', NULL, 1, 0),
(65, '7XXP-7H', 'Preylene', 'preylenep@gmail.com', 'Quotation', 'Good Morning\r\n\r\nI would like to know whether you can please forward me your e-mail address, as I have a cutting list and would like a quotation please.\r\n\r\nThank you.\r\nRegards\r\nPreylene', '2014-07-21 07:41:45', NULL, 1, 0),
(66, 'XEKZ-TJ', 'Joan Anthony', 'submissions@rtfs.co.za', 'Request for quotation', 'Good morning\r\n\r\nCan you please furnish me with an e-mail address in order to forward my requirement.\r\n\r\nMany thanks and kind regards,\r\n\r\nJoan', '2014-07-31 08:25:41', NULL, 1, 0),
(67, 'HF96-0Z', 'Sue Hahn', 'sueh@miltons.law.za', 'BORDER FOR A MIRROR', 'Hi i am looking for a beading / edging for a mirror to match my cupboards which are a dark mahoganny colour - there is already one mirror in my bathroom with a 60mm edging, bevelled on both sides - would you be able to assist me with this product?  Thanks', '2014-08-19 13:29:57', NULL, 1, 0),
(68, 'K3Z6-IB', 'john adams', 'homeadvisors@ovi.com', 'price', 'Hi I need price for white melamine sheets and oak top and cutting and delivery to paarl thank u.', '2014-10-23 10:07:45', NULL, 1, 0),
(69, 'WZJY-G5', 'Nqaba', 'southaafrican@hotmail.com', 'Quotation', 'I would like to have a build-in wardrobe in white melamine board, the room Length is 2,245 and Breadth is 2,225 \r\nThank you', '2014-10-30 08:49:10', NULL, 1, 0),
(70, 'WLZI-CK', 'John P', 'trafficinstitutionemail@aol.com', 'Can I assist you with www.boardsforafrica.co.za?', 'Hi, \r\n \r\nI''m John Pim, a marketing manager at Traffic Institution. I came across www.boardsforafrica.co.za and see that it has the potential to get a lot more visitors. \r\n \r\nI just wanted to tell you, in case you didn''t already know... We cater to over 7,000 small and medium biz and website owners - many in your niche, all seeing a TON more sales, subscribers and clickthroughs. \r\n \r\nWe''re network partners with the largest media banner networks - the same networks that serve traffic to hundreds of thousands of popular news, cooking, animal, research, shopping, etc websites you already use daily. \r\n \r\nSimply put, I think www.boardsforafrica.co.za can get a lot more exposure from buying and driving traffic the same way all of these other successful websites have been doing for so long! \r\n \r\nLet me give you all the details here: \r\nhttp://trafficinstitution.com/traffic-plans/ \r\n \r\nAll that any successful website is is simply visitors who come and want to visit, read and engage with it - could www.boardsforafrica.co.za genuinely benefit from any of these future events? \r\n \r\n- 100% real people clicking through from blogs and websites in your niche to your blog - ensuring the best chances of engagement, whether you want leads, email subscribers or sales? \r\n- MONTHLY visitors to set up once, and focus on improving your website appearance, salesfunnel, etc - never to have to worry about traffic again? \r\n- QUICK exposure, sales and brand awareness building for your website without spending $1,000s on SEO and social media and waiting months for rankings and followers to appear? \r\n \r\nIf your answer is YES to any of these, the answer is as simple as increasing the traffic to your website ASAP. Not having to worry about where to find quality visitors for your website is 70% of the overall hassle gone - so I hope I can assist you with that :) \r\n \r\nIf you''re ready and want to watch www.boardsforafrica.co.za explode with traffic ASAP - go here: http://trafficinstitution.com/traffic-plans/ \r\n \r\nIf you have any questions regarding if we have traffic in particular niches or countries - please email me at admin@trafficinstitution.com \r\n \r\nHere''s to your success and quick website growth!', '2014-11-03 15:39:10', NULL, 1, 0),
(71, 'J5UC-4W', 'Brian Goodwin', 'btgoodwin84@gmail.com', 'Saleem', 'I would like Saleem to contact me urgently please.', '2014-11-05 16:05:26', NULL, 1, 0),
(72, 'E4VM-30', 'Mario Paulse', 'mariop@net1.com', 'Quotation', 'Morning, \r\n\r\nI would like to get a formal quotation on the following please.\r\n\r\n-1200x500=2\r\n-1200x532=2\r\n-500x500=2\r\n\r\nAll white chipboards(16ml) with normal with edging on each cut.\r\n\r\nI hope all informatiom is in order.\r\n\r\nRegards\r\nMr Paulse.  \r\n0783515208........0', '2014-11-12 07:44:46', NULL, 1, 0),
(73, '1P2N-UM', 'Vee', 'sbovania@gmail.com', 'x100 Chipboards', 'Good day,\r\n\r\nPlease send me a quotation for 100 chipboards to be delivered in Witbank Mpumalanga', '2014-11-14 08:52:57', NULL, 1, 0),
(74, '9OHV-3R', 'Faried Howa', 'estimating@uriah.co.za', 'White Melamine', 'Please quote on the following;\r\n2 X 2050 X 450 E1L WHITE MEL\r\n2 X 870 X 450 E1L WHITE MEL\r\n2 X 1950 X 446 EAR 3 HOLES WHITE MEL\r\n1 X 870 X 100 WHITE MEL\r\n1 X 1950 X 900 WHITE HARDBOARD', '2014-11-28 08:48:15', NULL, 1, 0),
(75, 'CZIH-VP', 'Sennica Bacela', 'senni.bacela@gmail.com', 'Quote: Kitchen board material', 'Good day\r\n\r\nCould you please send me a quote for the following please.\r\n\r\n000945 Bison White Com. 9x6x16 8\r\n003020 Nova Lunar Ash Alp 9x6  4 \r\n003178 Edging PVC Lunar Ash 20mm 156\r\n031900 Cutting Mel. & Veneer 12\r\n030800 Hardboard WHT 8x4xx3.2 5\r\n031802 Cutting hardboard     5\r\n001113 Telescopic runner 500MME 4\r\nCB640 Chip screws 6x40 (100) 4\r\nCB630 Chip screws 6x30 (100) 2\r\nCB816 Chip screws 8x16 (100) 4\r\n002316 Hinge CABX Straight 60\r\n312300 Wire Nails 25MM 250G 4\r\n3605WT White Corner blocks 50\r\n003178 Edging PVC Lunar Ash20MM 10\r\n001367 POZI BIT NO.2 Gold LEN855 2\r\nIncluding a delivery to Samora Machel.', '2014-12-11 09:45:29', NULL, 1, 0),
(76, '4X9G-M9', 'Cindy_ Zhang', 'sara@syyoubangwood.com', 'Board factory in China, we manufacture UV MDF board, acrylic MDF board', 'Dear Sir,\r\n\r\nGlad to see your website.\r\nWe are a big and professional factory in China, manufacture UV MDF board, acrylic MDF board and UV HPL board. I note you aren''t dealing with these items. Are you interested in them?\r\nAppreciate your soon reply. And could you please give me the email of your purchasing manager?\r\n\r\nLooking forward to your reply.\r\n\r\nBest regards\r\n\r\nCindy\r\nShenyang Youbang Wood Industry Co., Ltd.', '2014-12-26 10:53:15', NULL, 1, 0),
(77, 'KKN6-EZ', 'Donna', 'emxtgosn@gmail.com', 'Donna', 'Hi, my name is Donna and I am the marketing manager at StarSEO Marketing. I was just looking at your site and see that your website has the potential to become very popular. I just want to tell you, In case you don''t already know... There is a website network which already has more than 16 million users, and most of the users are interested in topics like yours. By getting your website on this service you have a chance to get your site more visitors than you can imagine. It is free to sign up and you can read more about it here: http://2u4.us/1qky - Now, let me ask you... Do you need your website to be successful to maintain your business? Do you need targeted traffic who are interested in the services and products you offer? Are looking for exposure, to increase sales, and to quickly develop awareness for your website? If your answer is YES, you can achieve these things only if you get your site on the service I am talking about. This traffic network advertises you to thousands, while also giving you a chance to test the service before paying anything at all. All the popular websites are using this service to boost their readership and ad revenue! Why arenâ€™t you? And what is better than traffic? Itâ€™s recurring traffic! That''s how running a successful website works... Here''s to your success! Read more here: http://cmyad.co/i/5i1w', '2014-12-28 07:32:22', NULL, 1, 0),
(78, '3PBO-YZ', 'Angelina', 'vivplsaixd@hotmail.com', 'Angelina', 'Hi, my name is Angelina and I am the sales manager at StarSEO Marketing. I was just looking at your site and see that your site has the potential to get a lot of visitors. I just want to tell you, In case you don''t already know... There is a website network which already has more than 16 million users, and most of the users are interested in topics like yours. By getting your site on this service you have a chance to get your site more popular than you can imagine. It is free to sign up and you can find out more about it here: http://berjadigi.com/1DyG - Now, let me ask you... Do you need your website to be successful to maintain your way of life? Do you need targeted visitors who are interested in the services and products you offer? Are looking for exposure, to increase sales, and to quickly develop awareness for your website? If your answer is YES, you can achieve these things only if you get your website on the network I am talking about. This traffic service advertises you to thousands, while also giving you a chance to test the service before paying anything. All the popular blogs are using this network to boost their readership and ad revenue! Why arenâ€™t you? And what is better than traffic? Itâ€™s recurring traffic! That''s how running a successful website works... Here''s to your success! Read more here: http://shibam-news.com/i/ti', '2015-01-02 01:23:46', NULL, 1, 0),
(79, 'D8C2-JJ', 'Simone adams', 'simone.adams21@gmail.com', 'Qoute', 'hi there,\r\n\r\nCould I please have a quote for the following:\r\nLH door - 397(w) x 720(H)\r\nRH door - 397(w) x 720(h)\r\nDivider - 560(w) x 770(l)\r\n\r\nAll white melamine please.\r\n\r\nthank you.', '2015-02-02 09:46:46', NULL, 1, 0),
(80, 'DLZT-JP', 'vera wang', 'verawang@fushiwood.com', 'RE:plywood,marine plywood,H20 beam ,scaffolding LVL manufacturer To:Purchasing Manager', 'Dear sir or madam,\r\n \r\nNice to know you from internet.\r\n \r\nThis is vera wang from Shouguang Fushi Wood Co.,ltd in China producing plywood,film faced plywood(marine plywood),MDF,H20 beam,particle board.\r\n \r\ni am wondering whether we have chance to cooperate with you,\r\n \r\nnow we have many Africa customers such Nigeria,Kenya,Zambia and so on buying from us.\r\nso i want to know whether you need this kind of wood board.Hope we have chance to cooperate with you in the futher.\r\n \r\nThanks.\r\n \r\nRdgs.,\r\n \r\nVera Wang\r\n\r\n\r\n\r\n\r\n\r\n\r\nWe are leading and professional wood panel group in China \r\n\r\nSHOUGUANG FUSHI WOOD CO., LTD \r\n\r\n(PLYWOOD,LVL,MDF,PARTICLE BOARD,OSB Manufacturer)\r\n\r\nTEL: 86-536-5675257\r\n\r\nFAX: 86-536-5668257\r\n\r\nMOBILE: 86-15169602268\r\n\r\nMSN: vera-plywood@hotmail.com \r\n\r\nE-MAIL: verawang@fushiwood.com\r\n\r\nWEBSITE: www.fushiwood.com\r\n\r\nADD.: 58 FUSHI ROAD EAST CITY INDUSTRIAL ZONE SHOUGUANG SHANDONG CHINA', '2015-02-04 10:34:49', NULL, 1, 0),
(81, 'VDQN-20', 'Natasha Abrahams', 'natasha@interslab.co.za', 'Quote', 'Please send me your email adress so that i can send you what i need and you can give me a quote very URGENT. Send email adress to above mentioned email', '2015-02-17 13:14:04', NULL, 1, 0),
(82, 'QAU4-9H', 'Nikki', 'ettezacka@hotmail.com', 'Nikki', 'Hi, my name is Nikki and I am the sales manager at StarSEO Marketing. I was just looking at your Contact Us | Boards for Africa website and see that your website has the potential to get a lot of visitors. I just want to tell you, In case you don''t already know... There is a website service which already has more than 16 million users, and most of the users are interested in topics like yours. By getting your website on this network you have a chance to get your site more visitors than you can imagine. It is free to sign up and you can find out more about it here: http://1to.to/s5t - Now, let me ask you... Do you need your site to be successful to maintain your way of life? Do you need targeted traffic who are interested in the services and products you offer? Are looking for exposure, to increase sales, and to quickly develop awareness for your site? If your answer is YES, you can achieve these things only if you get your site on the service I am talking about. This traffic network advertises you to thousands, while also giving you a chance to test the network before paying anything at all. All the popular websites are using this service to boost their traffic and ad revenue! Why arenâ€™t you? And what is better than traffic? Itâ€™s recurring traffic! That''s how running a successful website works... Here''s to your success! Read more here: http://pixz.nu/1LQf', '2015-02-18 09:34:19', NULL, 1, 0),
(83, 'D2JM-B5', 'Devin', 'understoodyacht3c@rediffmail.com', 'Facebook management for www.boardsforafrica.co.za?', 'Hello, \r\n \r\nMy name is Devin Sorbert - I''m a media manager at Social Media Gurus. We''re a 3 person full social media management company based out of Greater Grand Rapids, Michigan. We handle account creation and growth for small businesses - and our 3rd partner has spent 3 years setting up Facebook and Google Adwords campaigns for small businesses for local lead generation for a Grand Rapids media management company before coming to work with us. \r\n \r\nI saw www.boardsforafrica.co.za and want to know if you''re interested in expanding your social media presence? Basically - more fans, likes and general engagement on your Facebook page? \r\n \r\nIt''s really easy - we''d do a free 15 minute consultation over phone or Skype - where we''ll fill out a simple questionnaire to figure out the specific social media needs for your business. I''ll show you some references and current clients pages that have consented to being used as examples (pet shelters and such) - and explain why more fans and activity on your page will help your business. If during the consultation we learn that you sell commercially/are happy with 10 fans on your page/have no business use for social media presence - I won''t sell you garbage. Chemical factories don''t need Facebook pages (unless they''d like a corporate page) - and I won''t argue with that. \r\n \r\nOur prices start at $189 a month for complete management and assistance of your media profile. Our prices reflect the service quality - if you''ve had bad experiences buying fans for $20 on Fiverr that were deleted/had your account suspended - we can rectify that. We run small media campaigns throughout the month creating natural fan growth to your page - no automated accounts or likes, and no chance of any account issues. We also do not need any security information to promote your page - anyone who does probably uses a form of automation to grow your account. \r\n \r\nCheck out these monthly plans to get a full idea of everything we do for your page and then send me a reply for your consultation :) \r\nhttp://socialmediagurus.net/ \r\n \r\nIf I can help you - reply back at emailsocialmediagurus@mail.com and we''ll set up a good time for you to create a plan for www.boardsforafrica.co.za. \r\n \r\nHope I can assist you, \r\nDevin', '2015-02-25 16:50:50', NULL, 1, 0),
(84, 'ENO1-A7', 'Taahira', 'tluckan91@gmail.com', 'materials', 'Hi i would like the price of your rhino board and also chip board. Do they come in certain sizes per sheet or are they cut to size. Thanks', '2015-02-27 01:16:04', NULL, 1, 0),
(85, '4R9D-HP', 'Manou | AfriCamps', 'manou@africamps.com', 'Kitchen worktops', 'Hey there, \r\n\r\nI''m looking for kitchen worktops (for example PG Bison), preferably with squareline edge.\r\n\r\n- What standard widths do you offer?\r\n- What colors do you have?\r\n\r\nWe need around 36 meter width in total, 0,6m deep (so for example 10 x 3,6 meters).\r\n\r\nCould you give me a price estimate?\r\n\r\nHope to hear from you soon\r\n\r\nKind Regards Manou', '2015-03-13 13:29:47', NULL, 1, 0),
(86, 'MW8H-6C', 'Chantal Steyn', 'Chantalsteyn22@gmail.com', 'Quotations Required - 15.03.2015', 'Good Day, Kindly forward a quotation for the below in (1)white melamine /(2) scale oak & (3)Larancina please, therefore 3 quotes required for the below please. H:710 , W: 495 E/AR  / H:710, W:500 E/AR 2 HOLES / H:710, W:415 E/AR / H:710, W:605  E/AR 2 HOLES/ H:160, W:445 (Ã—4) E/AR / H:660, W:580 E/AR 2 HOLES / H:660, W:555  E/AR 2 HOLES/ H:660, W:557 E/AR 2 HOLES/ H:660, W:680 E/AR 2 HOLES / H:660, W:447 E/AR 2 HOLES / H:490, W:448 (Ã—2) E/AR 2 HOLES / H:390, W:1100 (Ã—2) E / AR . THEN WHITE UTILITY BOARD:(HÃ—W) 195Ã—2.700 / 910Ã—570 E/AR / 400Ã—300 E/AR (Ã—2) / 400 Ã— 2100 E/AR (Ã—2). HARDBOARD WHITE: (HÃ—W) 2100Ã—400 / 2Ã— 3.6 U CHANNEL 20MM. Could you kindly forward Monday 16.03.2015 Please!  Kind Regards Chantal Steyn', '2015-03-15 17:03:42', NULL, 1, 0),
(87, 'OS92-LN', 'Harrison Zhou', 'harrison@southeastmdf.com', 'Chinese MDF supplier Looking for business opportunity', 'Dear sir or madam,\r\nGood day!\r\n\r\nThis is Harrison from Ningguo Southeast Wood Industry Co.,Ltd., which is a leading MDF supplier in China with production lines over China. Our products are raw MDF&HDF, melamine MDF, veneer faced MDF and MDF mounding. , etc.\r\n\r\nI hope we can get business cooperation with your company. Please donâ€™t hesitate to contact me if you have any questions, your reply will be highly appreciated.', '2015-03-21 09:50:24', NULL, 1, 0),
(88, '8TNO-JW', 'Wesley Moore (Yusuf Mohamed)', 'wez.moore@gmail.com', 'Quote ATT: Saleem', 'Hi Saleem, my friend/colleague Yusuf Mohamed just spoke to you.\r\n\r\nI would like a quote on Engineered stone for my kitchen.  I have a dimensioned drawing of the various tops I require.  Please supply me with an email address where I could send it to.\r\n\r\nThank you\r\n\r\nWesley Moore\r\n084 514 5283', '2015-03-30 15:36:30', NULL, 1, 0),
(89, 'S0A1-OS', 'Catherine', 'cqhuawopg@dayrep.com', 'Catherine', 'Hi, my name is Catherine and I am the sales manager at StarSEO Marketing. I was just looking at your Contact Us | Boards for Africa website and see that your site has the potential to become very popular. I just want to tell you, In case you don''t already know... There is a website service which already has more than 16 million users, and the majority of the users are looking for niches like yours. By getting your website on this service you have a chance to get your site more popular than you can imagine. It is free to sign up and you can find out more about it here: http://1be.info/3o3a - Now, let me ask you... Do you need your website to be successful to maintain your business? Do you need targeted visitors who are interested in the services and products you offer? Are looking for exposure, to increase sales, and to quickly develop awareness for your website? If your answer is YES, you can achieve these things only if you get your site on the service I am talking about. This traffic network advertises you to thousands, while also giving you a chance to test the service before paying anything. All the popular blogs are using this service to boost their traffic and ad revenue! Why arenâ€™t you? And what is better than traffic? Itâ€™s recurring traffic! That''s how running a successful site works... Here''s to your success! Read more here: http://cabkit.in/9mt5', '2015-04-04 21:01:07', NULL, 1, 0),
(90, 'NUAX-5U', 'marisha', 'marisha@kusa.co.za', 'laminated click and glue flooring', 'How much do you charge for the click and glue flooring', '2015-04-07 14:49:49', NULL, 1, 0),
(91, 'SGF4-8O', 'William', 'jdttimber@live.co.za', 'price list', 'Hi\r\nwe sell timber to the public and builders in the Cape Winelands. Can you send me a price list please ?\r\n\r\nRegards\r\nWilliam', '2015-04-07 20:41:46', NULL, 1, 0),
(92, 'TLY7-PD', 'Catherine', 'uhzvmbmnger@dayrep.com', 'Catherine', 'Hi, my name is Catherine and I am the sales manager at StarSEO Marketing. I was just looking at your Contact Us | Boards for Africa site and see that your site has the potential to become very popular. I just want to tell you, In case you don''t already know... There is a website service which already has more than 16 million users, and most of the users are interested in topics like yours. By getting your website on this network you have a chance to get your site more visitors than you can imagine. It is free to sign up and you can find out more about it here: http://9n3.us/6hpy - Now, let me ask you... Do you need your website to be successful to maintain your business? Do you need targeted traffic who are interested in the services and products you offer? Are looking for exposure, to increase sales, and to quickly develop awareness for your website? If your answer is YES, you can achieve these things only if you get your website on the network I am talking about. This traffic service advertises you to thousands, while also giving you a chance to test the network before paying anything. All the popular websites are using this network to boost their readership and ad revenue! Why arenâ€™t you? And what is better than traffic? Itâ€™s recurring traffic! That''s how running a successful website works... Here''s to your success! Read more here: http://tf3.info/nf', '2015-04-13 02:02:28', NULL, 1, 0);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
